// User action types
export const USER_LOG_IN = 'USER_LOG_IN';
export const USER_LOG_IN_SUCCESS = 'USER_LOG_IN_SUCCESS';
export const USER_LOG_IN_FAIL = 'USER_LOG_IN_FAIL';
export const USER_LOG_OUT_SUCCESS = 'USER_LOG_OUT_SUCCESS';
export const USER_LOG_OUT_FAIL = 'USER_LOG_OUT_FAIL';
export const USER_REGISTER_CHANGED = 'USER_REGISTER_CHANGED';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const USER_SET_CURRENT_USER = 'USER_SET_CURRENT_USER';
export const USER_LOAD_TV_SERIES_WISHLIST = 'USER_LOAD_TV_SERIES_WISHLIST';
export const USER_LOAD_MOVIES_WISHLIST = 'USER_LOAD_MOVIES_WISHLIST';

export const TV_SERIES_SEARCH = 'TV_SERIES_SEARCH';
export const TV_SERIES_SEARCH_SUCCESS = 'TV_SERIES_SEARCH_SUCCESS';
export const TV_SERIES_SEARCH_CLEAR = 'TV_SERIES_SEARCH_CLEAR';

export const MOVIES_SEARCH = 'MOVIES_SEARCH';
export const MOVIES_SEARCH_SUCCESS = 'MOVIES_SEARCH_SUCCESS';
export const MOVIES_SEARCH_CLEAR = 'MOVIES_SEARCH_CLEAR';
export const MOVIES_GET_DETAILS_SUCCESS = 'MOVIES_GET_DETAILS_SUCCESS';
